version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-modules:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directories:
      - /engines/html
      - /engines/jq
      - /engines/sql
      - /engines/text
      - /minimizers/redactor
    schedule:
      interval: weekly
    groups:
      standalone-go-modules:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
